### ISSUE TITLE
The example `a$$` is passing & there are no intellisense

### ISSUE THREAD

**Issue by iliaamiri** [Blaspsoft/blasp#10]
The Laravel News blog mentions that the library can also check for obscured words like (`a$$`) too. But, My test is failing when I try to check for that.

![image](https://github.com/user-attachments/assets/dc61b293-25be-497f-9d92-98dbfc776ef0)

And lastly, is there any way I can have a proper intellisense support for it? I can't get any type hinting (see below)
![image](https://github.com/user-attachments/assets/31899822-5511-448e-bfc9-0273515c6822)
![image](https://github.com/user-attachments/assets/8790e50a-7a85-452a-92bd-dd82dd53b3ab)

**Comment by deemonic** [comment]
Hi @iliaamiri thank you for bringing this to my attention I have replicated the issue you have reported.

This is strange as it appears to be only with $$ e.g. a$$ doesn't work but a55 does

I will take a look at this over the next few days to see if I can get it fixed.

Adding intellisense support is also a great idea

Many Thanks

**Comment by deemonic** [comment]
The issue with a$$ was due to the regex interpreting the $$ as a apart of the regex string. I have escaped this now and will release shortly.

**Comment by deemonic** [comment]
I have pushed a release which addresses the a$$ issue. Thank you for raising this I appreciate it 👍

I've not had time to look into the intellisense but I'm going to close this issue and put intellisense on the roadmap for a future release. Thank you for your suggestion and bringing this to me attention.

**Comment by iliaamiri** [comment]
Hey, thank you for the prompt fix! I appreciate it! 💯
