### ISSUE TITLE
The example afuckb is passing

### ISSUE THREAD

**Issue by c-andrews** [Blaspsoft/blasp#11]
The word **afuckb** doesnt get picked up but **afuck** does. Should the check happen for profanity contained inside a word?

**Comment by deemonic** [comment]
Hi @c-andrews thank you for reporting this edge case. I will take a look and work on a fix.

**Comment by c-andrews** [comment]
No problem thanks, I'll eagerly be waiting as we're trying to go live asap 😂.

**Comment by deemonic** [comment]
Wow! Okay, just out of curiosity what project have you used blasp in?

Also regarding your bug, what do l you think the expected output should be for this "afuckb"

1. a****b
2. ******

**Comment by iliaamiri** [comment]
Forgive my audacity, but i would just do a replace all for that specific case if i were in such a rush!

**Comment by deemonic** [comment]
@c-andrews I have a solution which addresses the issue you raised. I just need a day to implement and release. I'll keep you updated 👍

**Comment by c-andrews** [comment]
Thats amazing thank you @deemonic, its really appreciated!

**Comment by deemonic** [comment]
@c-andrews I pushed a release out which resolved the issue. Thank you for raising the issue it's much appreciated 👍

**Comment by c-andrews** [comment]
Amazing thanks you for sorting that out, its working perfectly. I had to update my **blasp.config** but once i sorted that it worked nicely.
